version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: shykoe
      MONGO_INITDB_ROOT_PASSWORD: Shykoetozx!2
    volumes:
      - /home/barry/mongodb/database:/data/db
    network_mode: host
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: shykoe
      ME_CONFIG_MONGODB_ADMINPASSWORD: Shykoetozx!2